config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :profile, only: %i(index update) do
    get :edit, on: :collection
  end
  resources :users, only: :show
  resources :posts, only: :show
  resources :search do
    get :index, on: :collection
    post :index, on: :collection
  end
  
  namespace :admin do
    resources :post_tags, only: %i(create destroy)
    resources :tags, only: %i(index new create destroy)
    resources :posts, only: %i(index new create edit update destroy)
    resources :preview do
      post :index, on: :collection
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_badge.html.erb
<span id=<%= "#{id_prefix}_#{dom_id(tag)}" %> class="inline-flex items-center px-2 py-1 my-1 rounded-md text-sm font-medium bg-pink-100 text-gray-800">
  <%= tag.name %>

  <% data = { data: { controller: 'confirm', confirm_text_value: "Are you sure you want to delete this tag? This can't be undone.", action: 'click->confirm#confirm' } } if defined?(confirm_message) %>

  <%= button_to path, data: data, class: "flex-shrink-0 ml-0.5 h-4 w-4 rounded-md inline-flex items-center justify-center text-pink-400 hover:bg-pink-200 hover:text-pink-500 focus:outline-none focus:bg-pink-500 focus:text-white" do %>
    <span class="sr-only">Remove large option</span>
    <svg class="h-2 w-2" stroke="currentColor" fill="none" viewBox="0 0 8 8">
      <path stroke-linecap="round" stroke-width="1.5" d="M1 1l6 6m0-6L1 7" />
    </svg>
  <% end %>
</span>

app/views/shared/_sign_in_buttons.html.erb
<div class="hidden md:flex items-center justify-end md:flex-1 lg:w-0">
  <%= link_to('Sign In', new_user_session_path, class: "whitespace-nowrap text-base font-medium text-pink-500 hover:bg-pink-100 border-2 px-3 py-1 border-pink-400 rounded-md") %>
  <%= link_to('Sign Up', new_user_registration_path, class: "ml-2 whitespace-nowrap inline-flex items-center justify-center bg-pink-600 hover:bg-pink-500 px-3 py-1 border border-transparent rounded-md shadow-sm text-base font-medium text-white hover:from-purple-700 hover:to-indigo-700") %>
</div>

app/views/shared/_toast.html.erb
<%= turbo_frame_tag 'toast' do %>
  <div class="flex w-full justify-center">
    <div
      data-controller="toast"
      data-toast-alert-value="<%= alert %>"
      data-toast-notice-value="<%= notice %>"
      class="fixed bottom-0 mb-6 hidden">
      <div data-toast-target="messageWrapper" class="shadow-md text-gray-800 rounded-md px-4 py-2">
        <span data-toast-target="message" class="block text-center"></span>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_topbar.html.erb
<nav class="bg-white border-b border-gray-200">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex justify-between h-16">
      <div class="flex">
        <div class="flex-shrink-0 flex items-center">
          <img class="block lg:hidden h-8 w-auto" src="https://tailwindui.com/img/logos/workflow-mark-indigo-600.svg" alt="Workflow">
          <img class="hidden lg:block h-8 w-auto" src="https://tailwindui.com/img/logos/workflow-logo-indigo-600-mark-gray-800-text.svg" alt="Workflow">
        </div>
        <div class="hidden sm:-my-px sm:ml-6 sm:flex sm:space-x-8">
          <!-- Current: "border-indigo-500 text-gray-900", Default: "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700" -->
          <%= link_to 'Home', root_path, class: "border-indigo-500 text-gray-900 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium" %>
        </div>
      </div>

      <div class="hidden sm:ml-6 sm:flex sm:items-center">
        <% if user_signed_in? %>
          <%= render 'shared/user_menu' %>
        <% else %>
          <%= render 'shared/sign_in_buttons' %>
        <% end %>
      </div>

      <div class="-mr-2 flex items-center sm:hidden">
        <!-- Mobile menu button -->
        <button type="button" class="bg-white inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" aria-controls="mobile-menu" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <!--
            Heroicon name: outline/menu

            Menu open: "hidden", Menu closed: "block"
          -->
          <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
          <!--
            Heroicon name: outline/x

            Menu open: "block", Menu closed: "hidden"
          -->
          <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
    </div>
  </div>

  <!-- Mobile menu, show/hide based on menu state. -->
  <div class="sm:hidden" id="mobile-menu">
    <div class="pt-2 pb-3 space-y-1">
      <!-- Current: "bg-indigo-50 border-indigo-500 text-indigo-700", Default: "border-transparent text-gray-600 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-800" -->
      <a href="#" class="bg-indigo-50 border-indigo-500 text-indigo-700 block pl-3 pr-4 py-2 border-l-4 text-base font-medium" aria-current="page">
        Dashboard
      </a>

      <a href="#" class="border-transparent text-gray-600 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-800 block pl-3 pr-4 py-2 border-l-4 text-base font-medium">
        Team
      </a>

      <a href="#" class="border-transparent text-gray-600 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-800 block pl-3 pr-4 py-2 border-l-4 text-base font-medium">
        Projects
      </a>

      <a href="#" class="border-transparent text-gray-600 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-800 block pl-3 pr-4 py-2 border-l-4 text-base font-medium">
        Calendar
      </a>
    </div>
    <div class="pt-4 pb-3 border-t border-gray-200">
      <div class="flex items-center px-4">
        <div class="flex-shrink-0">
          <img class="h-10 w-10 rounded-full" src="icons/avatar_placeholder.svg" alt="">
        </div>
        <div class="ml-3">
          <div class="text-base font-medium text-gray-800">Tom Cook</div>
          <div class="text-sm font-medium text-gray-500">tom@example.com</div>
        </div>
        <button class="ml-auto bg-white flex-shrink-0 p-1 rounded-full text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
          <span class="sr-only">View notifications</span>
          <!-- Heroicon name: outline/bell -->
          <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
          </svg>
        </button>
      </div>
      <div class="mt-3 space-y-1">
        <a href="#" class="block px-4 py-2 text-base font-medium text-gray-500 hover:text-gray-800 hover:bg-gray-100">
          Your Profile
        </a>

        <a href="#" class="block px-4 py-2 text-base font-medium text-gray-500 hover:text-gray-800 hover:bg-gray-100">
          Settings
        </a>

        <a href="#" class="block px-4 py-2 text-base font-medium text-gray-500 hover:text-gray-800 hover:bg-gray-100">
          Sign out
        </a>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_user_menu.html.erb
<div data-controller="dropdown" class="ml-3 relative">
  <div>
    <button data-action="click->dropdown#toggle click@window->dropdown#hide" type="button" class="max-w-xs bg-white flex items-center text-sm rounded-full focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-pink-500" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
      <span class="sr-only">Open user menu</span>
      <img class="h-8 w-8 rounded-full" src="icons/avatar_placeholder.svg" alt="">
    </button>
  </div>

  <div data-dropdown-target="dropdown" class="hidden origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg py-1 bg-white ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1">
    <%= link_to('Account', profile_index_path, class: 'text-left cursor-pointer block w-full px-4 py-2 text-sm text-gray-700 bg-white') %>
    <%= button_to('Sign Out', destroy_user_session_path, method: :delete, remote: true, class: 'text-left cursor-pointer block w-full px-4 py-2 text-sm text-gray-700 bg-white') %>
  </div>
</div>