config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :profile, only: %i(index update) do
    get :edit, on: :collection
  end
  resources :users, only: :show
  resources :posts, only: :show
  resources :search do
    get :index, on: :collection
    post :index, on: :collection
  end
  
  namespace :admin do
    resources :post_tags, only: %i(create destroy)
    resources :tags, only: %i(index new create destroy)
    resources :posts, only: %i(index new create edit update destroy)
    resources :preview do
      post :index, on: :collection
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/controllers/admin/post_tags_controller.rb
module Admin  
  class PostTagsController < BaseController
    def create
      @post_tag = PostTag.create!(post_id: params[:post_id], tag_id: params[:tag_id])
      @tags = Tag.where.not(id: Post.find(params[:post_id]).tag_ids).order(name: :asc)
    end
    
    def destroy
      @post_tag = PostTag.find(params[:id])
      @post_tag.destroy!
    end
  end
end

app/views/admin/post_tags/create.turbo_stream.erb
<%= turbo_stream.replace 'post_tags' do %>
  <% @tags.each do |tag| %>
    <%= render partial: 'shared/badge', locals: { tag: tag, path: admin_post_tag_path(post_id: @post_tag.post_id, tag_id: @post_tag.tag_id), method: :delete, id_prefix: :post_tags } %>
  <% end %>
<% end %>

app/views/admin/post_tags/destroy.turbo_stream.erb
<%= turbo_stream.remove "post_tags_#{dom_id(@post_tag.tag)}" %>

<%= turbo_stream.replace(:toast, partial: "shared/toast", locals: { notice: 'Tag removed!' }) %>