config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :profile, only: %i(index update) do
    get :edit, on: :collection
  end
  resources :users, only: :show
  resources :posts, only: :show
  resources :search do
    get :index, on: :collection
    post :index, on: :collection
  end
  
  namespace :admin do
    resources :post_tags, only: %i(create destroy)
    resources :tags, only: %i(index new create destroy)
    resources :posts, only: %i(index new create edit update destroy)
    resources :preview do
      post :index, on: :collection
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags

  validates_presence_of :title, :summary, :body, :parsed_body
  
  before_validation :parse_body

  private

  def parse_body
    self.parsed_body = MarkdownParser.new.parse(body)
  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < BaseController
    def new
      @post_tags = Post.none
      @post = Post.new
      @tags = Tag.order(name: :asc)
    end

    def create
      respond_to do |format|
        format.turbo_stream do
          result = PostsCreator.new(post_params).create_post

          if result.created?
            redirect_to root_path, notice: 'Post created!'
          else
            @post = result.post
            @post_tags = Post.where(id: post_params[:tag_ids])
            @tags = Tag.order(name: :asc)
          end
        end
      end
    end

    def edit
      @post = Post.friendly.find(params[:id])
      @tags = Tag.order(name: :asc)
    end

    def update
      respond_to do |format|
        format.turbo_stream do
          @post = Post.friendly.find(params[:id])

          result = PostsUpdater.new(@post, post_params).update_post

          if result.updated?
            redirect_to post_path(@post), notice: 'Post updated!'
          else
            @post_tags = Post.where(id: post_params[:tag_ids])
            @tags = Tag.order(name: :asc)
          end
        end
      end
    end

    def destroy
      post = Post.friendly.find(params[:id])

      post.destroy!

      redirect_to root_path, notice: 'Post deleted!'
    end

    private

    def post_params
      params.require(:post).permit(:title, :summary, :body, tag_ids: [])
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.friendly.find(params[:id])
  end
end

app/views/posts/_posts.html.erb
<%= turbo_frame_tag "posts_#{@page}", target: '_top' do %>
  <% if @page == 1 && @posts.size == 0 %>
    <p class="text-center mt-4 text-gray-500">No posts to show</p>
  <% else %>
    <% @posts.each do |post| %>
      <div class="pt-3 mb-6">
        <%= link_to post_path(post), class: "block rounded-md transition cursor-pointer group" do %>
          <h2 class="font-bold group-hover:underline mt-2"><%= post.title %></h2>
          <p class="text-gray-500"><%= post.summary %></p>
        <% end %>

        <div class="flex items-center">
          <span class="text-gray-400 m-0 text-sm"><%= post.created_at.strftime('%d %b %Y') %><span class="ml-2 mr-1">-</span></span>
          <div>
            <% post.tags.each do |tag| %>
              <%= basic_badge(tag) %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>

    <% if @has_next_page %>
      <%= turbo_frame_tag "posts_#{@next_page}", src: send(next_page_path, page: @next_page), loading: :lazy, target: '_top' do %>
        <%= render partial: 'shared/icons/loading', locals: { classes: 'w-10 h-10' } %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/posts/show.html.erb
<% content_for(:title) { @post.title } %>

<% content_for(:twitter_card) do %>
  <meta name="twitter:card" content="summary">
  <meta name="twitter:title" content="<%= @post.title %>">
  <meta name="twitter:description" content="<%= @post.summary %>">
  <meta name="twitter:image" content="https://miro.medium.com/max/1420/1*9hd_8qR0CMZ8L0pVbFLjDw.png">
  <meta name="twitter:site" content="@lewisyoul">
<% end %>

<div class="px-3 md:px-0 max-w-3xl mx-auto py-3">
  <h1 class="m-0 pt-12 text-center"><%= @post.title %></h1>
  <p class="text-center text-md text-gray-500 mt-2"><%= @post.created_at.strftime('%d %b %Y') %></p>

  <% if user_signed_in? %>
    <div class="flex justify-center">
      <%= link_to('Edit Post', edit_admin_post_path(@post), class: "mr-1 cursor-pointer whitespace-nowrap bg-white text-base font-medium text-pink-500 hover:bg-pink-100 border-2 px-3 py-1 border-pink-400 rounded-md") %>
      <%= button_to('Delete Post', admin_post_path(@post), method: :delete, data: { controller: 'confirm', confirm_text_value: "Are you sure you want to delete this post? This can't be undone.", action: 'click->confirm#confirm' }, class: "cursor-pointer whitespace-nowrap inline-flex items-center justify-center bg-pink-600 px-3 py-1 border border-transparent rounded-md shadow-sm text-base font-medium text-white") %>
    </div>
  <% end %>

  <div class="flex justify-center">
    <% @post.tags.each do |tag| %>
      <%= basic_badge(tag) %>
    <% end %>
  </div>

  <div id="post" class="pt-12">
    <%= raw(@post.parsed_body) %>
  </div>
</div>